Mouse position as touchpad finger position
Innoactive/IA-unity-VR-toolkit-VRTK pull request #2
Opened 2017-03-16 13:47 UTC by cutamar

2017-03-16 19:01 UTC, burnedikt requested changes

2017-03-16 19:01 UTC, burnedikt commented on VRTK/SDK/Simulator/SDK_InputSimulator.cs
> +                    ;
hässlich. Bitte lesbar machen ;) Mit klammern und so ...

2017-03-16 23:19 UTC, cutamar commented
war so klar haha

2017-03-17 08:20 UTC, burnedikt approved these changes

2017-03-17 08:21 UTC, burnedikt requested changes
Kannst du die zwei commits noch zu einem squashen? Sonst wirds später immer schwieriger, updates vom richtigen VRTK reinzupullen

2017-03-24 11:51 UTC, burnedikt requested changes

2017-03-24 11:51 UTC, burnedikt commented on VRTK/SDK/Simulator/SDK_InputSimulator.cs
> +                    ;
mach mal lieber 

```cs
 else if (Input.GetKey(touchpadAlias))
 {
     // Don't change controller position when touchpad is touched
 }
```

dann ist das hässliche semikolon weg und der Kommentar ist auch an ner sinnvollen stelle :P

2017-03-26 13:32 UTC, cutamar commented on VRTK/SDK/Simulator/SDK_InputSimulator.cs
> +                    ;
war schon absicht mit dem semicolon....aber ok..

2017-03-26 13:49 UTC, burnedikt approved these changes

2017-03-26 13:49 UTC, merged

2017-03-26 15:40 UTC, burnedikt commented on VRTK/SDK/Simulator/SDK_InputSimulator.cs
> +                    ;
hässlich.