properly restore previous use button state when using use button override
Innoactive/IA-unity-VR-toolkit-VRTK pull request #7
Opened 2017-06-21 15:48 UTC by dominik-rausch

2017-06-21 15:53 UTC, burnedikt requested changes

2017-06-21 15:53 UTC, burnedikt commented on Assets/VRTK/Scripts/Interactions/VRTK_InteractUse.cs
> +                    savedUseButton = VRTK_ControllerEvents.ButtonAlias.Undefined;
whitespace!!!!!!11111elf

2017-06-21 16:02 UTC, dominik-rausch commented
fixed whitespaces

2017-06-28 14:52 UTC, burnedikt commented
nope! No longer required due to different multi-grabbing implementation

2017-06-28 14:52 UTC, closed without merging